- hosts: all
  become: true
  tasks:
    - shell: /usr/local/bin/listsnapshot.sh
      args:
        executable: /bin/bash
      register: result
      changed_when: false 

    - debug:
        var: result.stdout

    - debug:
        var: result.stderr

    - fail:
        msg: >
          O script falhou com código de saída {{ result.rc }}.
          STDERR: {{ result.stderr }}
      when: result.rc != 0
