- hosts: all
  become: true
  tasks:
    - shell: /usr/local/bin/listsnapshot.sh
      args:
        executable: /bin/bash
      register: script_output
      changed_when: false

    - debug:
        msg: "{{ script_output.stdout_lines }}"

    - debug:
        msg: "{{ script_output.stderr_lines }}"

    - fail:
        msg: >
          O script falhou com código de saída {{ script_output.rc }}.
          STDERR: {{ script_output.stderr }}
      when: script_output.rc != 0
