---
- name: Atualizar sistema operacional conforme a distribuição
  hosts: all
  become: yes
  tasks:
    - name: Atualizar sistemas baseados em Debian (Debian/Ubuntu)
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Atualizar sistemas baseados em RedHat (RHEL/CentOS/Fedora)
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Atualizar sistema operacional Windows
      win_updates:
        category_names: ['Critical Updates', 'Security Updates']
        reboot: yes
      when: ansible_os_family == "Windows"
