---
- name: Atualizar sistema operacional conforme a distribuição
  hosts: all
  become: yes
  vars:
    debian_tags: "Debian/Ubuntu"
    redhat_tags: "RHEL/CentOS/Fedora"
    windows_tags: "Windows"
    reboot_required: false

  tasks:
    # Bloco para sistemas Linux (Debian, RedHat, etc.)
    - block:
        - name: Exibir mensagem para sistemas Linux
          debug:
            msg: "Iniciando atualização do sistema operacional para {{ ansible_distribution }}..."
        
        - name: Atualizar sistemas baseados em Debian (apt update e upgrade dist)
          apt:
            update_cache: yes
            upgrade: dist
          when: ansible_os_family == "Debian"
          tags: debian

        - name: Atualizar sistemas baseados em RedHat (yum update)
          yum:
            name: "*"
            state: latest
          when: ansible_os_family == "RedHat"
          tags: redhat

      when: ansible_os_family != "Windows"

    # Bloco para sistemas Windows (sem become)
    - block:
        - name: Exibir mensagem para sistemas Windows
          debug:
            msg: "Sistema Windows identificado. Iniciando atualização..."
        
        - name: Atualizar sistema operacional Windows
          win_updates:
            category_names: ['Critical Updates', 'Security Updates']
            reboot: no  # Reinicialização controlada pelo handler
          register: win_update_result
          tags: windows

        - name: Definir flag para reinicialização no Windows, se necessário
          set_fact:
            reboot_required: "{{ win_update_result.reboot_required | default(false) }}"
          tags: windows

      become: no
      when: ansible_os_family == "Windows"

  handlers:
    - name: Reiniciar o sistema se necessário (Windows)
      reboot:
        msg: "Reiniciando o sistema após atualizações críticas."
        pre_reboot_delay: 10
      when: reboot_required
      listen: "Reboot Handler"
