---
- name: Baixar e instalar o MSI x64 do VirtIO Win
  hosts: windows
  gather_facts: yes
  vars:
    base_url: "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio"

  tasks:
    - name: Obter a página do diretório "archive-virtio"
      uri:
        url: "{{ base_url }}/"
        return_content: yes
      register: virtio_page
      delegate_to: localhost

    - name: Extrair subdiretórios com versões
      set_fact:
        version_dirs: "{{ virtio_page.content | regex_findall('href=\"(virtio-win-[^\"]+/)\"') }}"

    - name: Exibir versões disponíveis
      debug:
        msg: "Versões disponíveis: {{ version_dirs | join(', ') }}"

    - name: Pausar e solicitar a versão desejada
      pause:
        prompt: "Informe a versão desejada (exemplo: virtio-win-0.1.266-1): "
      register: user_input

    - name: Definir a versão selecionada
      set_fact:
        selected_version: "{{ user_input.user_input | trim }}"

    - name: Obter a página do diretório da versão selecionada
      uri:
        url: "{{ base_url }}/{{ selected_version }}/"
        return_content: yes
      register: version_page
      delegate_to: localhost

    - name: Extrair links dos arquivos MSI x64 da página
      set_fact:
        msi_links: "{{ version_page.content | regex_findall('href=\"([^\"]*x64[^\"]*\\.msi)\"') }}"

    - name: Exibir MSI encontrados
      debug:
        msg: "Arquivos MSI encontrados: {{ msi_links | join(', ') }}"

    - name: Selecionar o MSI x64 desejado (primeiro da lista)
      set_fact:
        selected_msi: "{{ msi_links[0] }}"
      when: msi_links | length > 0

    - name: Construir URL completa do MSI
      set_fact:
        msi_url: "{{ base_url }}/{{ selected_version }}/{{ selected_msi }}"

    - name: Exibir URL do MSI
      debug:
        msg: "MSI a ser baixado: {{ msi_url }}"

    - name: Baixar o MSI do VirtIO Win x64 para a pasta Downloads do usuário
      win_get_url:
        url: "{{ msi_url }}"
        dest: "{{ ansible_env.USERPROFILE }}\\Downloads\\{{ selected_msi }}"
      register: download_result

    - name: Instalar o pacote MSI do VirtIO Win
      win_package:
        path: "{{ ansible_env.USERPROFILE }}\\Downloads\\{{ selected_msi }}"
        arguments: "/qn"
